### ISSUE TITLE
want IPv6 support

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/opte#10]
We want IPv6 support for both the overlay and underlay. This is probably two separate pieces of work but they will have a lot of overlap.

**Comment by bnaecker** [comment]
The first nibble of this is up in #238, which adds minimal support for handling IPv6 extension headers.

**Comment by bnaecker** [comment]
Some more pieces:

- [ ] #243 
- [ ] #244 
- [ ] #245

**Comment by rzezeski** [comment]
I feel like the main pieces of IPv6 are in place, with the last bit being #282. Given that it has it's own issue I'm going to close this one.
