### ISSUE TITLE
Remove the "external IP hack"

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/opte#236]
Once we have the ability to simulate Boundary Services we'll want to remove all code related to the "external IP hack". Below is a list of things to check for code to remove. It's not simply a matter of reverting the commits listed below, as some legit fixes are also intertwined. However, deleting anything commented with `XXX-EXT-IP` or gated behind `xde_ext_ip_hack` should allow the compiler to make sure you clean everything up.

- [ ] Grep for all instances of `XXX-EXT-IP` in the code.
- [ ] Commit `52176b99cc578f5b7b90f9bae8935013f961086c`
- [ ] Commit `23884d35aa7908e23accaa77f125a370ddf5c606`
- [ ] Commit `3ea62a9b77f58dbbbf7dd772362b0d008c548e87`
- [ ] Commit `1f8c0a1ed65b296da3876017ea0040bc1b4c6601`
- [ ] Commit `92a3ae21ffd9405a6897b5136410e2b11ee74005`
- [ ] Commit `14410f9420184702fa4b0ee134a0aa37216398eb`

**Comment by luqmana** [comment]
Remaining OPTE bits removed in #311
