### ISSUE TITLE
Update imports to use item-per-line

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/opte#258]
It's a lot easier to deal with merge conflicts when using an item-per-line import style. Let's update the source wholesale, in one commit. We could make use of rustfmt if we don't care about adding an unstable option (opte will be on nightly for the foreseeable future).

https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity

**Comment by bnaecker** [comment]
Completed by #266
