### ISSUE TITLE
Implement `AsRef<[u8]>` for address types

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/opte#264]
We're doing a lot of things like this:

```rust
let x = smoltcp::wire::RawHardwareAddress::from(&mac.bytes());
```

That's copying the bytes in `mac` into a new array, taking a ref to that, which `RawHardwareAddress` is [copying again](https://docs.rs/smoltcp/latest/src/smoltcp/wire/mod.rs.html#334). Maybe that's being optimized into one copy, I'm not sure. But it would be nice to be able to refer to the MAC and IP address types as arrays of immutable bytes in any case. Another thing this will make more ergonomic is DHCPv6 Unique IDs, where we'll likely use the link-layer address format. That's supposed to just be an opaque byte array, and so referring to a MAC like that will be nice.

We can do all of this by implementing `AsRef<[u8]>` for those array types, allowing us to just use them as byte arrays where that's convenient.

**Comment by rzezeski** [comment]
I think you completed this in the recent DHCPv6 work?

**Comment by bnaecker** [comment]
Yeah, thanks I meant to check that off. Done!
