### ISSUE TITLE
DNS values should come from VpcCfg

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/opte#270]
Currently we are hard-coding DHCP DNS entries in the `oxide-vpc` code. These should ultimately come from the control plane via the `VpcCfg`.

**Comment by bnaecker** [comment]
Same goes for time synchronization servers (NTP etc.) Maybe worth a separate issue to track that. Note that there's no control plane API for managing these yet.

**Comment by rzezeski** [comment]
Yes, let's make a separate issue for NTP. We don't have to wait for CP to have an abstraction, we can at least move the hard-coded values into sled-agent so that OPTE is ready to accept these configurations generically.

**Comment by bnaecker** [comment]
This issue should also cover adding support for the domain search list options the `VpcCfg`, and passing that in to the injected DHCP Offer and DHCPv6 Response messages. See https://github.com/oxidecomputer/omicron/issues/2153 for the Omicron side which will exercise this.

**Comment by bnaecker** [comment]
Closed by #324
