### ISSUE TITLE
The firewall needs some IPv6 love

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/opte#282]
Currently the `oxide_vpc::api::Address` type only supports IPv4. This is the type used to support firewall rules. We'll want to add some IPv6 support at some point now that we have some IPv6 connectivity implemented.

**Comment by bnaecker** [comment]
Note to self, this may be completed, need to audit.

**Comment by bnaecker** [comment]
Not done actually. It _looks_ like we just need to support both IPv4/IPv6 in the `oxide_vpc::api::Address` type for firewall rules to be expressed as V6 addresses or subnets. PR will be up later, pretty minimal.

**Comment by bnaecker** [comment]
Closed by #325
