### ISSUE TITLE
xde does not update VPC mappings when a Port is deleted

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/opte#294]
While integrating SoftNPU into Omicron, we currently need to explicitly tell SoftNPU about a port's state, which includes its VNI. That's retrieved from the output of `opteadm dump-v2p`. While doing that, I created one guest, but noticed the `dump-v2p` output included multiple VNIs. I deleted the guest, and the existing VNIs remained, i.e., there are now two VNIs, though no OPTE ports at all exist:

```bash
bnaecker@feldspar : ~/omicron $ pfexec opteadm list-ports
LINK                             MAC ADDRESS              IPv4 ADDRESS     EXTERNAL IPv4    IPv6 ADDRESS                             EXTERNAL IPv6                            STATE
bnaecker@feldspar : ~/omicron $ pfexec opteadm dump-v2p
Virtual to Physical Mappings
======================================================================

VPC 9826635
----------------------------------------------------------------------

IPv4 mappings
----------------------------------------------------------------------
VPC IP                   VPC MAC ADDR      UNDERLAY IP
172.30.0.5               A8:40:25:F1:6E:6F fd00:1122:3344:101::1

IPv6 mappings
----------------------------------------------------------------------
VPC IP                   VPC MAC ADDR      UNDERLAY IP

VPC 16441775
----------------------------------------------------------------------

IPv4 mappings
----------------------------------------------------------------------
VPC IP                   VPC MAC ADDR      UNDERLAY IP
172.30.0.5               A8:40:25:F9:1B:0F fd00:1122:3344:101::1

IPv6 mappings
----------------------------------------------------------------------
VPC IP                   VPC MAC ADDR      UNDERLAY IP
bnaecker@feldspar : ~/omicron $
```

It looks like the [`xde` handler](https://github.com/oxidecomputer/opte/blob/5de4c105dbfa5bea12fad889c1ad424c44b45c70/xde/src/xde.rs#L635) for the `delete-xde` ioctl removes the representation of the port from its driver state, but does not update the driver-wide V2P mapping to reflect the fact that the port is now gone.

I imagine this hasn't been an issue until now because (1) no one has really looked at the v2p mappings much, and (2) we've not hit various assertions about uniqueness in the V2P mapping because both VNIs and MACs are random, and there's a lot of bits in that combined space.

Regardless, we need to update the V2P mappings when we delete a port.

**Comment by rzezeski** [comment]
Addressed by #295 (e6e197a08c086cfa4cdb2e58bf71c580f89229ac).
