### ISSUE TITLE
opte/xde/ddm handoff

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#320]
When a packet from the guest has made it through opte, xde hands that packet off to the kernel to send out one of the two phys. Which of these phys is used should be determined by the ddm routing machinery. I believe this should already be happening based on how xde and ddm both currently work. But we need to verify this is the case.

**Comment by bnaecker** [comment]
I believe `xde` still arbitrarily picks the first underlay link when sending packets: https://github.com/oxidecomputer/opte/blob/master/xde/src/xde.rs#L1384.

**Comment by rcgoodfellow** [comment]
Ah yeah, it looks like the [next_hop function calls into the route selection function `ire_ftable_lookup_simple_v6`](https://github.com/oxidecomputer/opte/blob/master/xde/src/xde.rs#L1700-L1711) that [includes ddm route selection logic](https://github.com/oxidecomputer/illumos-gate/blob/stlouis-ddm/usr/src/uts/common/inet/ip/ip6_ire.c#L944-L967) but the result of that call is only used for [outer frame construction](https://github.com/oxidecomputer/opte/blob/master/xde/src/xde.rs#L1493-L1497) and not interface selection.
