### ISSUE TITLE
opte seems to be adding 40 bytes to payload size

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/opte#337]
After adc8cdc, opte seems to be adding 40 bytes to the payload size of outgoing GENEVE packets. Here's an example from a ping to an instance (10.1.0.101):

```
16:20:59.953213 IP6 (hlim 63, next-header UDP (17) payload length: 114) fd03:1122:3344:101::15.47783 > fd00:1122:3344:101::1.6081: [udp sum ok] Geneve, Flags [none], vni 0xba043f
        IP (tos 0x0, ttl 64, id 49097, offset 0, flags [DF], proto ICMP (1), length 84)
    10.0.0.1 > 10.1.0.101: ICMP echo request, id 21890, seq 2, length 64

16:20:59.953341 IP6 truncated-ip6 - 40 bytes missing!(hlim 128, next-header UDP (17) payload length: 154) fd00:1122:3344:101::1.7777 > fd03:1122:3344:101::15.6081: [bad udp cksum 0x0000 -> 0x6f76!] Geneve, Flags [none], vni 0x63
        IP (tos 0x0, ttl 64, id 41518, offset 0, flags [DF], proto ICMP (1), length 84)
    10.1.0.101 > 10.0.0.1: ICMP echo reply, id 21890, seq 2, length 64
```

Notice that tcpdump says `40 bytes missing!`

The ICMP reply packet arrives at the sidecar but is dropped due to the length check:

```
$ pfexec dtrace -n 'ip_drop_input:entry,ip_drop_output:entry { trace(stringof(arg0)); stack(); }'
dtrace: description 'ip_drop_input:entry,ip_drop_output:entry ' matched 2 probes
CPU     ID                    FUNCTION:NAME
 12  65401              ip_drop_input:entry   ipIfStatsInTruncatedPkts         
              ip`ip_check_length+0x131
              ip`ill_input_short_v6+0xca
              ip`ip_input_common_v6+0x283
              ip`ip_input_v6+0x1f
              ip`ip_rput_v6+0x71
              unix`putnext+0x233
              dld`dld_str_rx_fastpath+0x37
              dls`i_dls_link_rx+0x311
              mac`mac_rx_deliver+0x2e
              mac`mac_rx_soft_ring_process+0x1be
              mac`mac_rx_srs_proto_fanout+0x29a
              mac`mac_rx_srs_drain+0x2e5
              mac`mac_rx_srs_process+0x123
              mac`mac_rx_common+0x213
              mac`mac_rx+0xc6
              mac`mac_rx_ring+0x1f
              ixgbe`ixgbe_intr_rx_work+0x5c
              ixgbe`ixgbe_intr_msix+0x3f
              apix`apix_dispatch_by_vector+0x8c
              apix`apix_dispatch_lowlevel+0x1c
```

Looking closer in Wireshark, the message `[Expert Info (Warning/Protocol): IPv6 payload length exceeds framing length (114 bytes)]` appears on the IPv6 layer:

![Screenshot_2023-02-21_11-31-48](https://user-images.githubusercontent.com/2858890/220432344-b2836afc-037a-4ce8-a825-5c55c23b4e5d.png)

I've attached the pcap to this issue. `tcpdump` in the instance sees the icmp echo request come in, and generates the echo reply, so I don't think this is a hairpin generating these packets.

[cap.pcap.gz](https://github.com/oxidecomputer/opte/files/10796633/cap.pcap.gz)

**Comment by jmpesp** [comment]
Note when I say "The ICMP reply packet arrives at the sidecar", these are not real sidecars but a desktop machine acting like a sidecar (routing to fake boundary services)

**Comment by bnaecker** [comment]
The fixed portion of an IPv6 header is 40 bytes long. I'm wondering if we're not computed the pseudo-header correctly, or otherwise adding in the header length when we should be just inserting the payload length.

**Comment by bnaecker** [comment]
So I found a bug, but I don't know if it's _this_ bug. We were not correctly setting the Payload Length for IPv6 packets, if those packets included extension headers. I'll write this up in an issue.

**Comment by jmpesp** [comment]
@bnaecker the `guest_to_internet` integration tests generates these truncated packets. With the diff

```diff
diff --git a/oxide-vpc/tests/integration_tests.rs b/oxide-vpc/tests/integration_tests.rs
index 0a733ee..d038601 100644
--- a/oxide-vpc/tests/integration_tests.rs
+++ b/oxide-vpc/tests/integration_tests.rs
@@ -791,6 +791,10 @@ fn guest_to_internet() {
 
         ulp => panic!("expected inner TCP metadata, got: {:?}", ulp),
     }
+
+    let mut pcap_guest =
+        PcapBuilder::new("guest-to-internet.pcap");
+    pcap_guest.add_pkt(&pkt1);
 }
 
 // Verify that an ICMP Echo request has its identifier rewritten by
 ```

You can open `oxide-vpc/guest-to-internet.pcap` in Wireshark and see the same payload length warning.

**Comment by bnaecker** [comment]
Just to confirm, it looks like you're pinging the VPC subnet gateway, `10.0.0.1` from the guest, in your original packet capture. Is that correct?

**Comment by jmpesp** [comment]
In this case `10.0.0.1` lives on the other side of a GENEVE tunnel to the instance, and is on a Linux machine directly connected to the fake sidecar. The IP pool used here is `10.1.0.100 - 10.1.0.200`.

**Comment by jmpesp** [comment]
@bnaecker it's possible to have the test fail if the packet is truncated:

```diff
diff --git a/oxide-vpc/tests/integration_tests.rs b/oxide-vpc/tests/integration_tests.rs
index 0a733ee..1d26ccb 100644
--- a/oxide-vpc/tests/integration_tests.rs
+++ b/oxide-vpc/tests/integration_tests.rs
@@ -791,6 +791,14 @@ fn guest_to_internet() {
 
         ulp => panic!("expected inner TCP metadata, got: {:?}", ulp),
     }
+
+    use smoltcp::wire::Ipv6Packet;
+    use smoltcp::wire::EthernetFrame;
+
+    let bytes: Vec<u8> = pkt1.get_rdr().copy_remaining();
+
+    let packet = EthernetFrame::new_checked(&bytes).unwrap();
+    let packet = Ipv6Packet::new_checked(&packet.payload()[..]).unwrap();
 }
 
 // Verify that an ICMP Echo request has its identifier rewritten by
 ```

This fails with

```
---- guest_to_internet stdout ----
thread 'guest_to_internet' panicked at 'called `Result::unwrap()` on an `Err` value: Truncated', tests/integration_tests.rs:801:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
