### ISSUE TITLE
Hard coded DHCP DNS options 

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#390]
This line is causing problems and needs to be parameterized with the rack configured dns addresses.

https://github.com/oxidecomputer/opte/blob/e5423d80dff36e516cefba95ae35865173902bf4/lib/oxide-vpc/src/engine/gateway/dhcp.rs#L84

**Comment by askfongjojo** [comment]
See also https://github.com/oxidecomputer/omicron/issues/2153
