### ISSUE TITLE
Handle IPv4 options

### ISSUE THREAD

**Issue by luqmana** [oxidecomputer/opte#571]
Today we just swallow any IPv4 options we encounter and never emit any ourselves:

https://github.com/oxidecomputer/opte/blob/1201f219ffbf75d10d0ecd941ac36041a2aaf7ff/lib/opte/src/engine/ip4.rs#L379-L384

Need to decide if we'll just let them through as-is or on a per-option basis. Will we need to rewrite the contents on ingress/egress?

**Comment by FelixMcFelix** [comment]
It should be said that there is a bug in swallowing these options properly -- we need to adjust the IHL and total_length back down to baseline. As it stands, these are unchanged and so get fed back out when we generate a fresh IP header:

https://github.com/oxidecomputer/opte/blob/1201f219ffbf75d10d0ecd941ac36041a2aaf7ff/lib/opte/src/engine/ip4.rs#L546-L562

The better fix is just to correctly re-emit them, as I promised we should eventually do...
