### ISSUE TITLE
opte panic opte/src/engine/port.rs:1400:59 Option::unwrap() on a None value

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/opte#618]
Sled 21 in dogfood paniced in opte:

```
Dec 28 00:00:56 BRM42220031 savecore: [ID 570001 auth.error] reboot after panic: panicked at /work/oxidecomputer/opte/lib/opte/src/engine/port.rs:1400:59:                                                                                                                                  
Dec 28 00:00:56 BRM42220031 called `Option::unwrap()` on a `None` value 
```

The resulting core reports:
```
> ::status
debugging crash dump vmcore.0 (64-bit) from BRM42220031
operating system: 5.11 helios-2.0.23033 (oxide)
build version: heads/stlouis-0-g3a56ba873a
image uuid: f3d5155b-2b76-4a9f-9bed-124070e2687a
panic message: panicked at /work/oxidecomputer/opte/lib/opte/src/engine/port.rs:1400:59:
called `Option::unwrap()` on a `None` value
dump content: kernel pages and pages from PID -1
> 
```

And:
```
> ::stack                             
vpanic()
rust_begin_unwind+0x16d()
0xfffffffff84f3e8f()
core::panicking::panic_bounds_check::h675786dd45cde0b3()
0xfffffffff84f3398()
xde_mc_tx+0x4554()
mac_ring_tx+0x50(fffffcfbdfca3040, 0, fffffcfafeec62e0)
mac_provider_tx+0x6d(fffffcfbdfca3040, 0, fffffcfafeec62e0, fffffcfc072bfd78)
mac_tx+0x46c(fffffcfc072bfd78, fffffcfafeec62e0, 0, 1, 0)
viona_tx+0x322(fffffcfa706efdc0, fffffcfa706eff38)
viona_worker_tx+0x75(fffffcfa706eff38, fffffcfa706efdc0)
viona_worker+0x13a(fffffcfa706eff38)
thread_start+0xb()
```

**Comment by FelixMcFelix** [comment]
Thanks for the report -- I think I see what's happening here! Basically, this unwrap [used to be safe](https://github.com/oxidecomputer/opte/blob/f3002b356da7d0e4ca15beb66a5566a92919baaa/lib/opte/src/engine/port.rs#L1649-L1652). TCP state management was exclusively held within the port lock, and that removal succeeding was an invariant when all the locks were held.

Now, however, TCP state can be examined and decided upon outside of the port lock in the case of a UFT hit. This allows interactions like the following (where two packets access in/out flows with shared TCP state):
* TCP packet 1 grabs the port lock, retrieves its matching UFT entry. Port lock is dropped.
* TCP packet 2 grabs the port lock, retrieves its matching UFT entry. Port lock is dropped.
* TCP packet 1 locks the TCP state and updates it -- the flow is closed, but this packet does not require reprocessing. TCP lock is dropped.
* TCP packet 2 locks the TCP state and updates it -- the flow is closed, but this packet **does require reprocessing**. TCP lock is dropped.
* TCP packet 1 reacquires the port lock. TCP flow entry is removed, port lock is dropped. The packet undergoes fastpath processing.
* TCP packet 2 reacquires the port lock. The packet attempts to re-remove the flow state -- `panic!`.

All of this is a long way of saying: we need to lose the `.unwrap()`, but we also need to be careful to remove exactly the TCP state we saw (i.e., identical `Arc` values) to preserve the state of any flows who beat us to the cleanup branch.

**Comment by FelixMcFelix** [comment]
Thinking on it some more there is one other actor in play, which is the flow expiry timer. Every second XDE attempts to remove UFT entries and TCP flow entries which have not been used in a certain timeframe. For TCP entries, this is 120s if in TIME_WAIT and 2.5hrs if in any other state [noting that *most* flows are removed during close]. This is another potential source of a racing flow-delete.
