### ISSUE TITLE
Crash in `opte-core` during `pkg uninstall` operation

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/opte#63]
I'm running the falcon testbed environment [described here](https://github.com/oxidecomputer/testbed/tree/main/opte-ddm-x2), and hit a crash in `opte-core` when running `pkg uninstall entire`. The actual error was generated from [this line in `opte_core`](https://github.com/oxidecomputer/opte/blob/d40658718d9ff38d33ec906ca71c415ec2dd48cf/opte-core/src/packet.rs#L1733).

Below is a stack trace, and I can furnish a core dump on request.

```
root@sled1:/opt/cargo-bay# pkg uninstall entire
Creating Plan (Finding local manifests): \WARNING: panicked at 'called `Result::unwrap()` on an `Err` value: NotEnoughBytes { available: 2, needed: 2 }', /work/oxidecomputer/opte/opte-core/src/packet.rs:1379:30

panic[cpu1]/thread=fffffe038d1f4860: panicked at 'called `Result::unwrap()` on an `Err` value: NotEnoughBytes { available: 2, needed: 2 }', /work/oxidecomputer/opte/opte-core/src/packet.rs:1379:30

fffffe0006bd7be0 xde:rust_begin_unwind+8a ()
fffffe0006bd7c20 xde:_ZN4core9panicking9panic_fmt17h57ecffea894d5708E+2d ()
fffffe0006bd7ca0 xde:_ZN4core6result13unwrap_failed17h8b0544d770fab8d4E+6c ()
fffffe0006bd7da0 xde:_ZN9opte_core6packet39Packet$LT$opte_core..packet..Parsed$GT$12emit_headers17h66b99676854a7357E+9d7 ()
fffffe0006bd7ea0 xde:_ZN9opte_core4port35Port$LT$opte_core..port..Active$GT$7process17hd57f1082140ea294E+16b ()
fffffe0006bd8640 xde:xde_mc_tx+1d7 ()
fffffe0006bd8670 mac:mac_ring_tx+43 ()
fffffe0006bd86c0 mac:mac_provider_tx+85 ()
fffffe0006bd8780 mac:mac_tx+295 ()
fffffe0006bd87d0 dld:str_mdata_fastpath_put+8e ()
fffffe0006bd88e0 ip:ip_xmit+843 ()
fffffe0006bd8b30 ip:ire_send_wire_v4+345 ()
fffffe0006bd8bb0 ip:conn_ip_output+1d4 ()
fffffe0006bd8be0 ip:tcp_send_data+58 ()
fffffe0006bd8c90 ip:tcp_do_connect+541 ()
fffffe0006bd8d80 ip:tcp_connect+c9 ()
fffffe0006bd8e20 sockfs:so_connect+d6 ()
fffffe0006bd8e70 sockfs:socket_connect+2f ()
fffffe0006bd8f00 sockfs:connect+9c ()
fffffe0006bd8f10 unix:brand_sys_syscall+1fe ()
```

I've not been able to locate the actual source of the bug, but the error message could be more helpful. AFAICT, the message will always print the same number of bytes for `needed` and `available`, since they're just the result of pointer arithmetic that is infallible. The actual error condition is about whether the read position is beyond the current write position in the underlying `mblk`, so printing those values (along with the expected offset we tried to read) would be more valuable.

**Comment by rzezeski** [comment]
Note: This issue is fixed but I'm keeping it open until I have the time to come back around to my comment around the error message.

**Comment by rzezeski** [comment]
Okay, #223 covers the error message fix.
