### ISSUE TITLE
Xde + Propolis/Viona Integration Tracking Issue

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#74]
This issue is to track integration with viona.

## Background

The first pass at xde/viona integration did not "just work". While xde provides a mac interface and viona consumes a mac interface, the situation is not that simple. When viona sets up a mac client for the underlying network device it's using, the [mac_client_open call](https://github.com/oxidecomputer/illumos-gate/blob/master/usr/src/uts/i86pc/io/viona/viona_main.c#L727) as a zero value for flags. This means that either a subsequent `mac_unicast_add` is needed, or the device is a vnic which results in a tx data path implicitly. Alternatively, if the `MAC_OPEN_FLAGS_NO_UNICAST_ADDR` were used, like [xde does](https://github.com/oxidecomputer/opte/blob/master/xde/src/xde.rs#L802) on its underlying devices, a basic tx data path would be set up.

## Interim Solution

In the interim, for viona integration, we will just layer vnics atop xde devices and have viona use vnics. This should work.

## Solution

There are a few avenues to take here. The following list is a starting point, feel free to add others.

- **_Conditionally_** use `MAC_OPEN_FLAGS_NO_UNICAST_ADDR` in viona.
- **_Conditionally_** use `mac_unicast_add` in viona.
- Figure out what would need to be added to xde to allow it to work in the same way vnic does where this implicit tx path is created for mac clients.

## Related

Propolis currently assumes the underlying network device for a port is going to be a vnic [here](https://github.com/oxidecomputer/propolis/blob/master/propolis/src/hw/virtio/viona.rs#L62). This would need to be generalized. Perhaps [netadm-sys](https://oxidecomputer.github.io/netadm-sys/libnet/index.html) could be helpful here.

**Comment by luqmana** [comment]
Looking at the possible solutions, is using `MAC_OPEN_FLAGS_NO_UNICAST_ADDR` in viona enough? 

In [mac_client_open](https://github.com/oxidecomputer/illumos-gate/blob/06b650b02f3e47978b5928d2fe9cc3e5fae49585/usr/src/uts/common/io/mac/mac_client.c#L1461-L1463):
```c
	/*
	 * We will do mimimal datapath setup to allow a MAC client to
	 * transmit or receive non-unicast packets without waiting
	 * for mac_unicast_add.
	 */
	if (mcip->mci_state_flags & MCIS_NO_UNICAST_ADDR) {
		if ((err = mac_client_datapath_setup(mcip, VLAN_ID_NONE,
		    NULL, NULL, B_TRUE, NULL)) != 0) {
			goto done;
		}
	}
```

Seems like we'd have a basic data path but not receive unicast packets? Or can xde handle that fine (I saw mention of promiscuous mode).

**Comment by luqmana** [comment]
Ok, I got propolis working directly on top of xde without a VNIC. On the viona side, I basically went with option (2) to conditionally call `mac_unicast_add` if the link isn't a vnic. The [change](https://github.com/luqmana/illumos-gate/commit/a2bf5630b9642d8ecd74d0e7af4796f0b0ecfcea) itself is fairly small.

The [OPTE side changes](https://github.com/oxidecomputer/opte/commit/0cb2ccf93745adbaed86bde61506ba686df59bb1#diff-6e5f48eb55e5a46db0935c32b09bd98299626898bdc533cf60ebc73cf6b0318f) were also similarly small; just needed to remove the hack allowing the VNIC to have the guest mac address.

If there isn't anything I missed about this approach, I think the next step then would be getting the viona changes landed first.

cc @pfmooney AFAIK viona seems to almost exclusively be used with just vnic's today but is there any reason I shouldn't do the `mac_unicast_add` changes as opt-in instead?

**Comment by luqmana** [comment]
Upstream illumos [issue](https://www.illumos.org/issues/15256) & [CR](https://code.illumos.org/c/illumos-gate/+/2558).

**Comment by rcgoodfellow** [comment]
Do we think this is still a good thing to spend time on for MVP?
